name: 'Auto Labeler'
description: 'Automatically labels PRs based on changed files'
author: 'Manpreet Singh'
inputs:
  token:
    description: 'GitHub token'
    required: false
    default: '${{ github.token }}'
  config_path:
    description: 'Path to labels.json'
    required: false
    default: '.github/labels.json'

runs:
  using: 'node16'
  main: 'dist/index.js'
