name: Check Action

on: pull_request

permissions:
  contents: read
  issues: write # needed to add labels to issues/PRs
  pull-requests: write # optional, for extra PR actions

jobs:
  check-action:
    name: Check Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Test Local Action
        id: test-action
        uses: ./

      - name: Print Output
        id: output
        run:
          echo "Output from action is ${{ steps.test-action.outputs.output }}"
